language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: mat.tabasko@gmail.com
  api_key:
    secure: XGsXms6uoCAKzwrWsjlPbDu9Zf0wXt4klE/eBKVWR6Rs5vH/Pq2rFExisXuByYozE3f6E1EnTsjkm4uAhHJNgGc6TlLivvTO2gUDdkrRcePOHzGNoHf40kDzSLvadig/FHtXg1WrUPMm7NJ15IN1ycMm7/2NxHEtA8aqCa441Gc=
